// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

declare global {
  interface Window {
    ENV?: Record<string, string | undefined>;
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const processEnv = (globalThis as any).process?.env || {};

  // Prefer processEnv (server) or window.ENV (client), fall back to import.meta.env
  const SUPABASE_URL =
    (typeof window !== "undefined" ? window.ENV?.VITE_SUPABASE_URL : undefined) ||
    processEnv.VITE_SUPABASE_URL ||
    processEnv.SUPABASE_URL ||
    import.meta.env.VITE_SUPABASE_URL;

  const SUPABASE_KEY =
    (typeof window !== "undefined" ? window.ENV?.VITE_SUPABASE_ANON_KEY : undefined) ||
    processEnv.VITE_SUPABASE_ANON_KEY ||
    processEnv.SUPABASE_ANON_KEY ||
    processEnv.SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_KEY ? ["SUPABASE_ANON_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your environment.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
